[package]
name = "hol"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Fetch the source of a single Rust item by name or path, optionally from a git ref."
repository = "https://github.com/t4lz/accio"
keywords = ["rust-analyzer", "source", "extract", "git", "ast"]
categories = ["development-tools"]

[features]
git = ["git2"]

[dependencies]
anyhow = "1.0"
ra_ap_ide = "0.0.301"
syn = "2.0"
git2 = { optional = true, version = "0.20" }

[dev-dependencies]
indoc = "2.0"